### ISSUE TITLE
E5113: Error while calling lua chunk: ...hare/nvim/site/pack/paqs/start/vgit.nvim/lua/vgit/ui.lua:72: attempt to index local 'config' (a nil value)

### ISSUE THREAD

**Issue by collegeimprovements** [tanvirtin/vgit.nvim#78] opened 2021-08-02 19:06 UTC
### Description

Thanks a lot for this awesome plugin.

I use `Paq` as plugin manager. 
I tried to uninstall and reinstall `VGit`.
I keep getting `E5113: Error while calling lua chunk: ...hare/nvim/site/pack/paqs/start/vgit.nvim/lua/vgit/ui.lua:72: attempt to index local 'config' (a nil value)` error.

<img width="1489" alt="Screenshot 2021-08-03 at 12 32 49 AM" src="https://user-images.githubusercontent.com/1519705/127910734-a19f62b9-cf60-455b-93e9-5da3d4a538f4.png">

After this error, I'm not able to use the plugin (i.e. VGit command doesn't appear/work in commandbar at the bottom).
This problem has appeared just recently after updating the plugin.

- nvim --version output: 
```
λ › nvim --version                                                                                                                                     Blocks/cloche_api ueberauth
Found existing alias for "nvim". You should use: "n"
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
λ ›                                                          
```
- Operating system: Mac Big Sur
- Terminal: Kitty

**Comment by tanvirtin** [comment] 2021-08-02 23:16
Hey, sorry this was caused by a recent refactor commit. Should be fixed now!

**Closed** 2021-08-02 23:16 UTC
Labels: bug

**Comment by collegeimprovements** [comment] 2021-08-03 04:19
Thanks a lot for quick response and fix.
